services:
  db:
    image: mysql:8.4
    environment:
      - MYSQL_DATABASE=walleton
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_USER=walleton
      - MYSQL_PASSWORD=changeme
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 40s
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: walleton
      DB_USER: walleton
      DB_PASS: changeme
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
